{"name": "Crear Perfil", "status": "broken", "statusDetails": {"message": "NameError: name 'true' is not defined\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\user_profile.py\", line 24, in create_profile\n    \"isContactInfoPublic\": true,\n                           ^^^^\n"}, "description": "Given: soy un usuario nuevo", "steps": [{"name": "When se envia una solicitud para crear un perfil con datos aleatorios", "status": "broken", "statusDetails": {"message": "NameError: name 'true' is not defined\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\user_profile.py\", line 24, in create_profile\n    \"isContactInfoPublic\": true,\n                           ^^^^\n"}, "start": 1715894708921, "stop": 1715894708925}, {"name": "Then se recibe una respuesta exitosa despues de crear el perfil", "status": "skipped", "start": 1715894708925, "stop": 1715894708925}], "start": 1715894708920, "stop": 1715894708925, "uuid": "fa1301bf-9a08-447c-8cba-68cef4e9ebb9", "historyId": "c7d516dc77cf9414fadcbe5c6e41bb2c", "fullName": "Gestión de Perfiles: Crear Perfil", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Gestión de Perfiles"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}